# See https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions

name: CI

on: [push, pull_request]

jobs:
  Package:
    runs-on: ubuntu-latest
    container:
      image: registry.opensuse.org/yast/sle-15/sp6/containers/yast-cpp:latest

    steps:

    - name: Git Checkout
      uses: actions/checkout@v2

    - name: Prepare System
      run: zypper --non-interactive in --no-recommends libcurl-devel

    - name: Package Build
      run:  yast-ci-cpp

  Checks:
    runs-on: ubuntu-latest
    # there is also ruby code, so for testing it use ruby container

    strategy:
      fail-fast: false

    container:
      image: registry.opensuse.org/yast/sle-15/sp6/containers/yast-ruby

    steps:

    - name: Git Checkout
      uses: actions/checkout@v2

    - name: syntax
      run:  rake check:syntax

    - name: pot
      run:  rake check:pot
