# See https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions

name: CI

on: [ push, pull_request ]

jobs:
  Package:
    # skip in master, but run in forks
    if:  github.ref_name != 'master' || github.repository_owner != 'yast'

    runs-on: ubuntu-latest
    container:
      image: registry.opensuse.org/yast/head/containers/yast-cpp:latest

    steps:
      - name: Git Checkout
        uses: actions/checkout@v2

      - name: Prepare System
        run: zypper --non-interactive in --no-recommends libcurl-devel

      - name: Package Build
        run: yast-ci-cpp

  Checks:
    runs-on: ubuntu-latest
    # there is also ruby code, so for testing it use ruby container

    strategy:
      fail-fast: false
      matrix:
        distro: [ "tumbleweed" ]

    container:
      image: registry.opensuse.org/yast/head/containers_${{matrix.distro}}/yast-ruby

    steps:
      - name: Git Checkout
        uses: actions/checkout@v2

      - name: syntax
        run: rake check:syntax

      - name: pot
        run: rake check:pot
